version: '3.8'

services:
  redis:
    image: redis:7.4-alpine
    container_name: ai-html-builder-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-html-builder-app
    restart: unless-stopped
    ports:
      - "8080:8000"
    environment:
      # Copy from your .env file or set via environment
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - MAX_UPLOAD_SIZE=52428800
      - SESSION_TIMEOUT=3600
      - RATE_LIMIT_REQUESTS=30
      - RATE_LIMIT_WINDOW=60
      - FRONTEND_URL=http://localhost:8080
      - BACKEND_URL=http://localhost:8080
      - JWT_SECRET=${JWT_SECRET:-ai-html-builder-jwt-secret-key-2025-secure}
      # Set your API keys via environment variables or .env
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
    driver: local